import { apiClient } from "./axios";

export const adminApi = {
  login: (data) => apiClient.post("/admin/login", data),
  dashboard: (token) => apiClient.get("/admin/dashboard", { headers: { Authorization: `Bearer ${token}` } }),
  users: (token, params) => apiClient.get("/users", { headers: { Authorization: `Bearer ${token}` }, params }),
  createUser: (token, data) => apiClient.post("/users", data, { headers: { Authorization: `Bearer ${token}` } }),
  updateUser: (token, id, data) => apiClient.put(`/users/${id}`, data, { headers: { Authorization: `Bearer ${token}` } }),
  deleteUser: (token, id) => apiClient.delete(`/users/${id}`, { headers: { Authorization: `Bearer ${token}` } }),
  roles: (token) => apiClient.get("/roles", { headers: { Authorization: `Bearer ${token}` } }),
  categories: (token) => apiClient.get("/categories", { headers: { Authorization: `Bearer ${token}` } }),
  products: (token) => apiClient.get("/products", { headers: { Authorization: `Bearer ${token}` } }),
  shipping: (token) => apiClient.get("/shipping", { headers: { Authorization: `Bearer ${token}` } }),
  orders: (token, params) => apiClient.get("/orders", { headers: { Authorization: `Bearer ${token}` }, params }),
  orderById: (token, id) => apiClient.get(`/orders/${id}`, { headers: { Authorization: `Bearer ${token}` } }),
  updateOrderStatus: (token, id, data) => apiClient.put(`/orders/${id}/status`, data, { headers: { Authorization: `Bearer ${token}` } }),
  assignOrderAgent: (token, id, data) => apiClient.put(`/orders/${id}/assign-agent`, data, { headers: { Authorization: `Bearer ${token}` } }),
  updateShipping: (token, id, data) => apiClient.put(`/orders/${id}/shipping`, data, { headers: { Authorization: `Bearer ${token}` } }),
  orderInvoice: (token, id) => apiClient.get(`/orders/${id}/invoice`, { headers: { Authorization: `Bearer ${token}` } }),
  printOrder: (token, data) => apiClient.post(`/orders/print`, data, { headers: { Authorization: `Bearer ${token}` } }),
  orderAgents: (token) => apiClient.get(`/orders/agents`, { headers: { Authorization: `Bearer ${token}` } }),
  payments: (token) => apiClient.get("/payments", { headers: { Authorization: `Bearer ${token}` } }),
  coupons: (token) => apiClient.get("/coupons", { headers: { Authorization: `Bearer ${token}` } }),
  reviews: (token) => apiClient.get("/reviews", { headers: { Authorization: `Bearer ${token}` } }),
  reports: (token, type) => apiClient.get(`/reports/${type}`, { headers: { Authorization: `Bearer ${token}` } }),
  settings: (token) => apiClient.get("/settings", { headers: { Authorization: `Bearer ${token}` } }),
  saveSettings: (token, data) => apiClient.put("/settings", data, { headers: { Authorization: `Bearer ${token}` } }),
  analyticsWishlist: (token) => apiClient.get("/analytics/wishlist", { headers: { Authorization: `Bearer ${token}` } }),
  analyticsCart: (token) => apiClient.get("/analytics/cart", { headers: { Authorization: `Bearer ${token}` } }),
  setupPermanentAdmin: (token, data) => apiClient.post("/admin/setup-permanent", data, { headers: { Authorization: `Bearer ${token}` } }),
};
